# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
		
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize [ "createmedium", "disk", "--filename", "disk2.vmdk", "--format", "vmdk", "--size", 1024 * 40  ]
        vb.customize [ "storageattach", :id , "--storagectl","IDE", "--port", "1", "--device", "0", "--type", "hdd", "--medium", "disk2.vmdk" ]
      end
      box.vm.synced_folder ".", "/vagrant", disabled: true
 	    box.vm.provision "shell", inline: <<-SHELL
	    mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
	    yum install -y mdadm smartmontools hdparm gdisk
  	  SHELL
    end
  end
end

